name: iOS list files workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - run: | 
         some_response=$(ls -R)
         echo response_output=$some_response >> $GITHUB_OUTPUT
         id: some-request
      - run: |
         echo "Response is: ${{ steps.some-request.outputs.response_output }}"
