name: iOS list files workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Just print all files
    runs-on: macos-latest
    steps:
      - name: Dump file hierarchy
        run: ls -R
