name: iOS list files workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job-1:
    name: Just print all files
    runs-on: macos-latest
    outputs:
      output1: ${{ steps.run_tests.outputs.test }}
    steps:
      - id: run_tests
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - name: Dump file hierarchy
        run: echo ${{steps.run_tests.outputs.test}}
           
