name: iOS list files workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job-1:
    name: Just print all files
    runs-on: macos-latest
    steps:
      - id: run_tests
        run: echo "output=${ls -R}" >> $GITHUB_OUTPUT
      - name: Dump file hierarchy
        run: echo ${{steps.run_tests.outputs.output}}
           
