name: iOS list files workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    name: Just print all files
    runs-on: macos-latest
    outputs:
      output1: ${{ steps.run_tests.outputs.test }}
    steps:
      - id: run_tests
        run: |
          echo "test=hello" >> $GITHUB_OUTPUT
          echo ${{job1.outputs.output1}}
    
