name: iOS list files workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    name: Just print all files
    runs-on: macos-latest
    steps:
      - id: run_tests
        run: 
          echo "test=$(ls -R)" >> $GITHUB_OUTPUT
      - name: dumping
        run:
          echo ${{join(steps.run_tests.outputs.*, '\n')}}
